server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  # Config Server (configuracion provisional)
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/